version: "3.7"

# networks:
#   - sailor

services:
  # -------------------------------------------------
  # NGINX -> via port 8088
  # -------------------------------------------------
  nginx:
    image: nginx:stable-alpine
    ports:
      - "8000:80"
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - node

  # -------------------------------------------------
  # PHP-FPM
  # -------------------------------------------------
  php:
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    volumes:
      - ./:/var/www/html
    command: "php artisan serve --host=0.0.0.0 --port=8000"

  # -------------------------------------------------
  # MYSQL SERVER - via port 33601
  # -------------------------------------------------
  # mysql:
  #   image: mysql:8.0.27
  #   restart: unless-stopped
  #   tty: true

  #   ports:
  #     - "33061:3306"

  #   environment:
  #     MYSQL_DATABASE: homestead
  #     MYSQL_USER: mrlijan
  #     MYSQL_PASSWORD: secret
  #     MYSQL_ROOT_PASSWORD: supersecret
  #     SERVICE_TAGS: dev
  #     SERVICE_NAME: mysql

  # -------------------------------------------------
  # Composer
  # -------------------------------------------------
  composer:
    image: composer:latest
    volumes:
      - ./:/var/www/html
    working_dir: /var/www/html

  node:
    image: node:current-alpine
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    environment:
      NODE_ENV: development
    command: "npm run hot"
    depends_on:
      - php
